# Form implementation generated from reading ui file 'Error_message.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Error_message(object):
    def setupUi(self, Error_message):
        Error_message.setObjectName("Error_message")
        Error_message.resize(400, 300)
        self.OK_pushButton = QtWidgets.QPushButton(parent=Error_message)
        self.OK_pushButton.setGeometry(QtCore.QRect(150, 180, 93, 28))
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.label = QtWidgets.QLabel(parent=Error_message)
        self.label.setGeometry(QtCore.QRect(10, 30, 381, 111))
        self.label.setOpenExternalLinks(True)
        self.label.setObjectName("label")

        self.retranslateUi(Error_message)
        QtCore.QMetaObject.connectSlotsByName(Error_message)

    def retranslateUi(self, Error_message):
        _translate = QtCore.QCoreApplication.translate
        Error_message.setWindowTitle(_translate("Error_message", "Form"))
        self.OK_pushButton.setText(_translate("Error_message", "OK"))
        self.label.setText(_translate("Error_message", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Something went wrong...</span></p></body></html>"))
